[[plugins]]
repo = 'Shougo/ddc.vim'
depends = ['denops.vim']
hook_add = '''
call ddc#custom#patch_global('ui', 'native')
call ddc#custom#patch_global('sources', ['lsp', 'around'])
call ddc#custom#patch_global('sourceOptions', {
     \ '_': {
     \ 'matchers': ['matcher_head'],
     \ 'sorters': ['sorter_rank'],
     \ 'converters': ['converter_remove_overlap'],
     \ },
     \ 'around': {'mark': 'A'},
     \ 'lsp': {
     \   'mark': 'L',
     \   'forceCompletionPattern': '\.\w*|:\w*|->\w*',
     \ },
     \ })

call ddc#custom#patch_global('sourceParams', {
     \ 'around': {'maxSize': 500},
     \ })
" <TAB>: completion.
inoremap <silent><expr> <TAB>
\ pumvisible() ? '<C-n>' :
\ (col('.') <= 1 <Bar><Bar> getline('.')[col('.') - 2] =~# '\s') ?
\ '<TAB>' : ddc#map#manual_complete()

" <S-TAB>: completion back.
inoremap <expr><S-TAB>  pumvisible() ? '<C-p>' : '<C-h>'

call ddc#enable()
'''

[[plugins]]
repo = 'Shougo/ddc-ui-native'

[[plugins]]
repo = 'Shougo/ddc-source-lsp'

[[plugins]]
repo = 'Shougo/ddc-source-around'

[[plugins]]
repo = 'Shougo/ddc-matcher_head'

[[plugins]]
repo = 'Shougo/ddc-sorter_rank'

[[plugins]]
repo = 'Shougo/ddc-converter_remove_overlap'
